### PR TITLE
Small Animals being skinned/plucked/gathered

### PR DESCRIPTION
**Pull request by AndrewR3K**
# Small Animals
---

## What exactly was added
- Added `givenAmount`
  - set to {0} will apply the standard min/max random. higher than 0 will give that amount of the item.
- Added `SmallAnimals` config
- Added js `DataViewNativeGetEventData` export. Thanks, @outsider31000 for linking this in the discord!
- 

## Instructions
- Pelt image needs to be added to VORP_Inventory (Or don't use pelt)
- Update DB with Pelt (Or don't use pelt)

## Notes
More small animals should/need to be added to config.

### CODE REVIEW

**Comment by outsider31000** [comment]
So with this where the items you hunt will go to? Inventory?

**Comment by outsider31000** [comment]
And thanks @AndrewR3K

**Comment by AndrewR3K** [comment]
Yup! I leverage the same `vorp_hunting:giveReward` server event like selling the animals to the main butcher, plus the ability to set a custom amount for item rewards. 😄 

[/client/main.lua#L287](https://github.com/AndrewR3K/VORP-Hunting/blob/small-animals/vorp_hunting/client/main.lua#L287
)

**Comment by outsider31000** [comment]
Allright thanks 😊

**Pull request merged**
