### PR TITLE
optimizations

### PR DESCRIPTION
**Pull request by jakeyboi1**
Was scrounging around the code, and noticed it looks old, incredibly outdated, and hasnt been updated in a bit. Did some small optimizations, and standardizing to help performance, and just in general make the code better to read and look at.

- In the config there is an option to set max allowed pelts on horse but in the client you hard limit it too 3 so even if the owner set the config to 5 it will only allow 3 to be stored on a horses. This makes 0 sense as why even have the config option if you limit it in the code itself so it has been removed in this pr.
- Uses lua54's joaat native instead of GetHashKey
- While loop waits modified slightly to improve performance around a .01ms decrease in resource usage on resmon after the changes
- Minor code cleanups, and removed unused variables

### CODE REVIEW

**Comment by outsider31000** [comment]
because you cant store more than 3 pelts no matter the amount you put

**Comment by jakeyboi1** [comment]
ahh valid just tossed the limiter back in along with a comment in the config to clarify that hard limit

**Comment by outsider31000** [comment]
image
what was the reason to remove this break ? so if you found the item why should it continue to loop ?

image
why did you have to remove the brackets ?  they are conferting the variables to true or false statments 

image
i also dont understand  why all lthe while loops were increased  when theres prompts to be shown that need to have a check at all frames

**Comment by jakeyboi1** [comment]
The break was not removed ofcourse that is less optimal it was just moved onto the same line skinfound = k which was right below the red code loll not sure how you didnt see that
image

the brackets are just not needed so why have them there it makes the code uglier for no reason

the while loops do not need to be so low 5ms works perfectly fine and increases performance by adding a few more ms of wait

**Comment by outsider31000** [comment]
`and noticed it looks old, incredibly outdated,` 
this statement did not make much sense because anything you changed had nothing to do with being incredible outdated
removing wording symbolizing that this script will run with fivem runtime `Citizen`, and adding joaats doesnt nor really make it up to date

**Comment by outsider31000** [comment]
nothing you did made it up to date neither optimised i dont see why this should be merged as it looks like its just a preference

**Comment by jakeyboi1** [comment]
It is litrally just a performance thing. It lowered the amount of resources the script uses in resmon, breaks nothing, and makes the code a bit easier to read. Not sure why you wouldnt merge it lol

**Comment by outsider31000** [comment]
because it adds nothing  to it its just a preference in code like removing brackets that you have no idea what they are for , waits need to be at 0 not everyone uses the same computers  , your statment said its incredible outdated , nothing you added made it up to date

**Comment by outsider31000** [comment]
you want to make it up to date add notifications with API for example, use vorp utils as well
you wnt to make it optimised add sleeping controllers to the threads increasing wait times does not work for everyone with slower computers the promtps will blink

**Comment by jakeyboi1** [comment]
You are completely correct Outsider

**Pull request closed without merging**
