### PR TITLE
updated legendary elk ped hash per latest research

### PR DESCRIPTION
**Pull request by 76cb**

### CODE REVIEW

**Comment by 76cb** [comment]
updated legendary elk ped hash per latest research

**Comment by outsider31000** [comment]
Can you post where you got this hash please 
also 
image
 this was comment  but only the dashes were removed

**Comment by 76cb** [comment]
the link is here https://redlookup.com/peds/?p=1&s=elk&at=-781967776

I removed the dashes in the pull because both models are called now with the elk / legendary elk

**Comment by outsider31000** [comment]
Did you test this? or did you just assume the link is right?

yes you removed the dashes but left the brackets, they need to be removed too...

**Comment by outsider31000** [comment]
feel free to open again when you want to fix this.

**Pull request closed without merging**
